# Generated by Django 5.1.1 on 2024-10-19 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("firms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalclient",
            name="firm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="firms.firm"
            ),
        ),
    ]
