# Generated by Django 5.1.1 on 2024-10-31 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generalclient",
            options={
                "verbose_name": "General Client",
                "verbose_name_plural": "General Clients",
            },
        ),
        migrations.AlterModelOptions(
            name="poolinvestmentclient",
            options={
                "verbose_name": "Pool Investment Client",
                "verbose_name_plural": "Pool Investment Clients",
            },
        ),
    ]
