# Generated by Django 5.1.1 on 2024-11-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_generalclient_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poolinvestmentclient",
            name="payments",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
