# Generated by Django 5.1.1 on 2024-11-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_poolinvestmentclient_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalclient",
            name="payments",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
