# Generated by Django 5.1.1 on 2025-01-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_generalclient_joined_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poolinvestmentclient',
            name='nav_value',
        ),
    ]
