# Generated by Django 5.1.1 on 2024-10-19 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="symbol"
                    ),
                ),
                (
                    "security_name",
                    models.CharField(max_length=100, verbose_name="security name"),
                ),
            ],
            options={
                "verbose_name": "Security",
                "verbose_name_plural": "Securities",
                "ordering": ["security_name"],
            },
        ),
        migrations.CreateModel(
            name="SecurityData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_traded_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="last traded price",
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="open price",
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="high price",
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="low price",
                    ),
                ),
                (
                    "previous_close",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="previous close",
                    ),
                ),
                (
                    "last_updated_datetime",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="last updated datetime",
                    ),
                ),
                (
                    "security",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nepse.security",
                        verbose_name="security",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Data",
                "verbose_name_plural": "Security Datas",
                "ordering": ["security"],
            },
        ),
    ]
