# Generated by Django 5.1.1 on 2024-10-16 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=100, unique=True)),
                ("security_name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["security_name"],
            },
        ),
        migrations.CreateModel(
            name="SecurityData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_traded_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "open_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "high_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "low_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "previous_close",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "last_updated_datetime",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "security",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="nepse.security"
                    ),
                ),
            ],
            options={
                "ordering": ["security"],
            },
        ),
    ]
