# Generated by Django 5.1.1 on 2024-10-16 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nepse", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="security",
            options={
                "ordering": ["security_name"],
                "verbose_name": "Security",
                "verbose_name_plural": "Securities",
            },
        ),
        migrations.AlterModelOptions(
            name="securitydata",
            options={
                "ordering": ["security"],
                "verbose_name": "Security Data",
                "verbose_name_plural": "Security Datas",
            },
        ),
        migrations.AlterField(
            model_name="security",
            name="security_name",
            field=models.CharField(max_length=100, verbose_name="security name"),
        ),
        migrations.AlterField(
            model_name="security",
            name="symbol",
            field=models.CharField(max_length=100, unique=True, verbose_name="symbol"),
        ),
        migrations.AlterField(
            model_name="securitydata",
            name="high_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="high price"
            ),
        ),
        migrations.AlterField(
            model_name="securitydata",
            name="last_traded_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="last traded price",
            ),
        ),
        migrations.AlterField(
            model_name="securitydata",
            name="last_updated_datetime",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="last updated datetime",
            ),
        ),
        migrations.AlterField(
            model_name="securitydata",
            name="low_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="low_price"
            ),
        ),
        migrations.AlterField(
            model_name="securitydata",
            name="open_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="open price"
            ),
        ),
        migrations.AlterField(
            model_name="securitydata",
            name="previous_close",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="previous close",
            ),
        ),
        migrations.AlterField(
            model_name="securitydata",
            name="security",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="nepse.security",
                verbose_name="security",
            ),
        ),
    ]
