# Generated by Django 5.1.1 on 2024-10-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nepse", "0002_alter_security_options_alter_securitydata_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securitydata",
            name="low_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="low price"
            ),
        ),
    ]
