# Generated by Django 5.1.1 on 2024-11-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="subscription_is_active",
            field=models.BooleanField(default=True),
        ),
    ]
