# Generated by Django 5.1.1 on 2024-10-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firm",
            name="clients",
        ),
    ]
