# Generated by Django 5.1.1 on 2024-11-01 06:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0002_firmexecutives"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FirmExecutives",
            new_name="FirmExecutive",
        ),
        migrations.AlterModelOptions(
            name="firmexecutive",
            options={
                "verbose_name": "Firm Executive",
                "verbose_name_plural": "Firm Executives",
            },
        ),
    ]
