# Generated by Django 5.1.1 on 2024-11-01 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0003_rename_firmexecutives_firmexecutive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firmexecutive",
            name="role_created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="firmmanager",
            name="role_created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
