# Generated by Django 5.1.1 on 2024-12-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_up_capital', models.DecimalField(decimal_places=2, help_text='Total paid-up capital.', max_digits=15)),
                ('total_share_units', models.PositiveIntegerField(help_text='Total number of share units.')),
            ],
        ),
        migrations.CreateModel(
            name='FundDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_at_bank', models.DecimalField(decimal_places=2, help_text='Cash available in the bank.', max_digits=15)),
                ('cash_on_hold', models.DecimalField(decimal_places=2, help_text='Cash on hold due to IPO applications.', max_digits=15)),
                ('fund_reserve', models.DecimalField(decimal_places=2, help_text='Reserve funds.', max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unreleased_profit', models.DecimalField(decimal_places=2, help_text='Profit that is not yet realized.', max_digits=15)),
                ('distributable_profit', models.DecimalField(decimal_places=2, help_text='Profit available for distribution.', max_digits=15)),
                ('operational_cost', models.DecimalField(decimal_places=2, help_text='Operational cost.', max_digits=15)),
            ],
        ),
    ]
