# Generated by Django 5.1.1 on 2024-12-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CapitalDetails',
            new_name='CapitalDetail',
        ),
        migrations.RenameModel(
            old_name='FundDetails',
            new_name='FundDetail',
        ),
        migrations.RenameModel(
            old_name='ProfitDetails',
            new_name='ProfitDetail',
        ),
    ]
