# Generated by Django 5.1.1 on 2025-01-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_rename_capitaldetails_capitaldetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitaldetail',
            name='nav_value',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
