# Generated by Django 5.1.1 on 2024-10-19 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("firms", "0002_remove_firm_clients"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.generalclient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoolInvestmentPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "firm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="firms.firm"
                    ),
                ),
            ],
        ),
    ]
