# Generated by Django 5.1.1 on 2024-11-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poolinvestmentportfolio",
            name="name",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
    ]
