# Generated by Django 5.1.1 on 2024-10-19 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firms", "0002_remove_firm_clients"),
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientportfolio",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="firms.firm",
            ),
        ),
        migrations.AlterField(
            model_name="poolinvestmentportfolio",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="firms.firm",
            ),
        ),
    ]
