# Generated by Django 5.1.1 on 2024-11-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0002_poolinvestmentportfolio_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientportfolioentry",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="clientportfolioentry",
            name="description",
        ),
        migrations.RemoveField(
            model_name="poolinvestmentportfolioentry",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="poolinvestmentportfolioentry",
            name="description",
        ),
        migrations.AddField(
            model_name="clientportfolioentry",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientportfolioentry",
            name="rate",
            field=models.PositiveIntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientportfolioentry",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="poolinvestmentportfolioentry",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poolinvestmentportfolioentry",
            name="rate",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poolinvestmentportfolioentry",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
