# Generated by Django 5.1.1 on 2024-11-01 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nepse", "0001_initial"),
        ("portfolios", "0003_remove_clientportfolioentry_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientportfolioentry",
            old_name="total",
            new_name="total_investment",
        ),
        migrations.RenameField(
            model_name="poolinvestmentportfolioentry",
            old_name="total",
            new_name="total_investment",
        ),
        migrations.AddField(
            model_name="clientportfolioentry",
            name="security",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="nepse.security",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poolinvestmentportfolioentry",
            name="security",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="nepse.security",
            ),
            preserve_default=False,
        ),
    ]
