# Generated by Django 5.1.1 on 2024-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_rename_total_clientportfolioentry_total_investment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientportfolioentry',
            name='total_investment',
        ),
        migrations.RemoveField(
            model_name='poolinvestmentportfolioentry',
            name='total_investment',
        ),
        migrations.AlterField(
            model_name='clientportfolioentry',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='poolinvestmentportfolioentry',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
