# Generated by Django 5.1.1 on 2024-12-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_remove_clientportfolioentry_total_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientportfolioentry',
            name='type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4),
        ),
        migrations.AddField(
            model_name='poolinvestmentportfolioentry',
            name='type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4),
        ),
    ]
