# Generated by Django 5.1.1 on 2024-12-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_clientportfolioentry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientportfolioentry',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poolinvestmentportfolioentry',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
