# Generated by Django 5.1.1 on 2024-12-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_clientportfolioentry_remaining_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientportfolioentry',
            name='remaining_quantity',
        ),
        migrations.RemoveField(
            model_name='clientportfolioentry',
            name='type',
        ),
        migrations.RemoveField(
            model_name='poolinvestmentportfolioentry',
            name='remaining_quantity',
        ),
        migrations.RemoveField(
            model_name='poolinvestmentportfolioentry',
            name='type',
        ),
        migrations.AddField(
            model_name='clientportfolioentry',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poolinvestmentportfolioentry',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4),
            preserve_default=False,
        ),
    ]
